services:
  web-portfolio:
    image: nginx
    container_name: 'portfolio-nginx'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx/nginx.${RUN_ENV}.conf:/etc/nginx/nginx.conf'
      - './site:/var/www/html/portfolio'
      - './ssl:/etc/nginx/ssl/'
    networks:
      - api-network
    depends_on:
      - api-web-porfolio
  api-web-porfolio:
    image: node
    container_name: 'porfolio-api'
    expose:
      - 5000
    volumes:
      - '.:/portfolio-project'
    working_dir: /portfolio-project
    command: sh script/${RUN_ENV}.sh
    environment:
      PRIVATE_CAPTCHA_KEY: ${PRIVATE_CAPTCHA_KEY}
    networks:
      - api-network
networks:
  api-network:
    driver: bridge
