services:
  web-portfolio:
    #  image: portfolio-image
    #  build:
    #    dockerfile: ./porfolio.local.dev.dockerfile
    image: nginx
    container_name: 'portfolio'
    ports:
      - '80:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './site:/var/www/html/portfolio'
  api-web-porfolio:
    image: node
    container_name: 'porfolio-api'
    expose:
      - 5000
    ports:
      - '3000:5000'
    volumes:
      - '.:/portfolio-project'
    working_dir: /portfolio-project
    command: npm run api:start:dev
