all:
  children:
    web:
      hosts:
        webserver:
          ansible_host: "{{ lookup('env', 'PORTFOLIO_HOST') }}"
          ansible_user: "{{ lookup('env', 'PORTFOLIO_HOST_USER') }}"
          ansible_ssh_private_key_file: ./keys/portolio-server-key.pem
      vars:
        RUN_ENV: prod
