name: CI Build and Test
on: [push] # The event that triggers the workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      # - name: Install dependencies
      #   run: npm install
      #   working-directory: ./api

      # - name: Build project
      #   run: npm run build
      #   working-directory: ./api

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: Copy package.json to S3
      #   run: aws s3 cp ./api/package.json s3://your-bucket-name/

      # - name: Copy dist folder to S3
      #   run: aws s3 cp ./api/dist s3://your-bucket-name/dist/ --recursive
